### ISSUE TITLE
max_questions is not working in MCQ's

### ISSUE THREAD

**Issue by aravind-812** [ramsrigouthamg/Questgen.ai#12]
When i add  max_questions to the payload and feed in a number like 10. It is only able to generate 4 questions at maximum.
Did the contributors intentionally restricted it to 4, or is there any scope of increasing it in any other way?
And what is the recommended number of words for the "input_text" in MCQ generation?

Thanks

**Comment by ramsrigouthamg** [comment]
@aravind-812 The max questions limited by I guess 4. 
The reason is that for T5 to generate more in parallel the inference time is longer. Hence I guess it is limited. 

The recommended word length can be anywhere between 100 - 1000 words etc. Although there is no physical limit keyword algorithm emphasizes inital words.

**Comment by aravind-812** [comment]
Gotcha @ramsrigouthamg 
Thanks.

**Comment by Yawan-1** [comment]
so, How exactly I can increase the number of questions (MCQ) to generate?

**Comment by GitVHV** [comment]
> vậy, chính xác thì tôi có thể tăng số lượng câu hỏi (MCQ) để tạo như thế nào?

Well it's simply increasing the word count in your paragraph

**Comment by Yawan-1** [comment]
@GitVHV Well, I don't use it anymore and won't recommend to anyone.
